joy_teleop/teleop_twist_joy_node:
  ros__parameters:

    # General behavior
    require_enable_button: true
    enable_button: 4            # LB
    enable_turbo_button: 5      # RB

    # Linear motion: left stick vertical (Y-axis)
    axis_linear:
      x: 1                      # Left stick vertical
      y: -1
      z: -1

    scale_linear:
      x: 0.5
      y: 0.0
      z: 0.0

    scale_linear_turbo:
      x: 1.0
      y: 0.0
      z: 0.0

    # Angular motion: right stick horizontal (X-axis)
    axis_angular:
      yaw: 3                    # Right stick horizontal
      pitch: -1
      roll: -1

    scale_angular:
      yaw: 0.5
      pitch: 0.0
      roll: 0.0

    scale_angular_turbo:
      yaw: 1.0
      pitch: 0.0
      roll: 0.0

    # Optional features
    inverted_reverse: false
    publish_stamped_twist: false
    frame: "teleop_twist_joy"
joy_teleop/joy_node:
  ros__parameters:  #deadzone: 0.1
    deadzone: 0.2
    autorepeat_rate: 20.0
    dev: /dev/input/js0

